name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: ["main"]  # деплой при пуше в main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Blazor WebAssembly
        run: dotnet publish ./SkopeoWebsite.csproj -c Release -o release --nologo
      
      - name: Fix blazor.boot.json paths for GitHub Pages
        run: |
          # Fix assembly paths (only if not null)
          jq 'if .resources.assembly != null then .resources.assembly |= with_entries(.key = "/SkopeoWebsite/_framework/" + .key) else . end' release/wwwroot/_framework/blazor.boot.json > temp.json
          mv temp.json release/wwwroot/_framework/blazor.boot.json
          
          # Fix pdb paths (only if not null)
          jq 'if .resources.pdb != null then .resources.pdb |= with_entries(.key = "/SkopeoWebsite/_framework/" + .key) else . end' release/wwwroot/_framework/blazor.boot.json > temp.json
          mv temp.json release/wwwroot/_framework/blazor.boot.json
          
          # Fix jsModuleRuntime paths (only if not null)
          jq 'if .resources.jsModuleRuntime != null then .resources.jsModuleRuntime |= with_entries(.key = "/SkopeoWebsite/_framework/" + .key) else . end' release/wwwroot/_framework/blazor.boot.json > temp.json
          mv temp.json release/wwwroot/_framework/blazor.boot.json
          
          # Fix jsModuleNative paths (only if not null)
          jq 'if .resources.jsModuleNative != null then .resources.jsModuleNative |= with_entries(.key = "/SkopeoWebsite/_framework/" + .key) else . end' release/wwwroot/_framework/blazor.boot.json > temp.json
          mv temp.json release/wwwroot/_framework/blazor.boot.json
          
          # Fix wasmNative paths (only if not null)
          jq 'if .resources.wasmNative != null then .resources.wasmNative |= with_entries(.key = "/SkopeoWebsite/_framework/" + .key) else . end' release/wwwroot/_framework/blazor.boot.json > temp.json
          mv temp.json release/wwwroot/_framework/blazor.boot.json
          
          # Fix icu paths (only if not null)
          jq 'if .resources.icu != null then .resources.icu |= with_entries(.key = "/SkopeoWebsite/_framework/" + .key) else . end' release/wwwroot/_framework/blazor.boot.json > temp.json
          mv temp.json release/wwwroot/_framework/blazor.boot.json
      
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
